### ISSUE TITLE
Incorrect Version 0.0.0 is shown in google-play

### ISSUE THREAD

**Issue by emanuelb** [shesek/spark-wallet#179]
Visit:
https://play.google.com/store/apps/details?id=com.spark.wallet

Shows "Current Version: 0.0.0"

probably the VersionCode/VersionName is set incorrectly in android build?

while latest release on github is 0.2.17
https://github.com/shesek/spark-wallet/releases

**Comment by shesek** [comment]
Thanks for reporting this!

The `versionCode` (internal non-user-visible incrementing integer version number) was being updated correctly, but the `versionName` which is what's visible on the Play Store was indeed not. This should now be fixed by d7ea4870c96d885aad57253417e782ffa02b3700.

And just to clarify, the release on the Play Store does match the latest on GitHub releases (versionName=0.2.17 / versionCode=219).
