### ISSUE TITLE
Enable Javascript alert

### ISSUE THREAD

**Issue by bitpaint** [shesek/spark-wallet#183]
Hey, 
from Tor browser i get a blank page if i when JavaScript is disabled.
Maybe a little text alert asking the user to enable Javascript in his browser could be good?

**Comment by shesek** [comment]
Hi @bitpaint, thanks for reporting this!

There was supposed to be a message shown when JavaScript is disabled, but it appears like it didn't work properly on some browsers. This should now be fixed by db4d78c65cd035877041d6843903d06af28b6c31 (still unreleased, will soon be available in the next version)
