### ISSUE TITLE
problems with Android app 0.2.1

### ISSUE THREAD

**Issue by leblitzdick** [shesek/spark-wallet#45]
Hi,
since my update to Android APP version 0.2.1 i get the error -> "Error: connection to server lost" . With APP version 0.1.3 everything is fine, also with the 0.2.1 server software running on my rpi3.
The same Problem with the 0.2.1 Versions for linux for me. 
Only the connection through https://91.xxx.xxx.96:9737 from my client is working, so i think my network configuration works, otherwise it wouldn't work either?!

I guess that something might not work with my keys,tls in the new version...?

thanks

**Comment by shesek** [comment]
I think this might be because your server doesn't have a trusted TLS certificate.

Prior to v0.2.0-rc.3, the `spark-wallet-x.y.z-android.apk` that was uploaded to GitHub releases was created as a "debug build", which is meant for development and is allowed to communicate with servers that has invalid TLS certificates.

Starting at v0.2.0-rc.3, I'm now uploading two `apk` files: `spark-wallet-x.y.z-android-debug.apk` which is the same as the previous debug build, and `spark-wallet-x.y.z-android-release.apk` which is a "release build" that is signed using my Google Play Store signing keys, but which cannot communicate with servers that has an invalid certificate.

You can do one of these:

- Switch back to using [the "debug" `apk` build](https://github.com/shesek/spark-wallet/releases/download/v0.2.1/spark-wallet-0.2.1-android-debug.apk).

- Setup a CA-signed TLS certificate using [the LetsEncrypt integration](https://github.com/shesek/spark-wallet/blob/master/doc/tls.md#letsencrypt-integration) (pretty easy, but requires a (sub)domain name pointed at your server).

- [Add your certificate to your android device as a User Trusted Certificate](https://github.com/shesek/spark-wallet/blob/master/doc/tls.md#add-as-trusted-certificate-to-android).

- [Setup your Spark server as a Tor hidden service](https://github.com/shesek/spark-wallet/blob/master/doc/onion.md).

- Setup your Spark server without TLS using `--no-tls`. This is *highly not* recommended unless you'll be using something else to encrypt communications, like a VPN tunnel.

**Comment by shesek** [comment]
Also note that the Android app is [published to the Play Store](https://play.google.com/store/apps/details?id=com.spark.wallet) now. If you want to be able to install from there, you won't be able to the debug build.

**Comment by leblitzdick** [comment]
OK, thanks, so long you provide a "debug" Version i will use it, that's fine for me because everything is under my control and there is no security problem for me!

thanks for the clarification

i close this!
