### ISSUE TITLE
Show off-chain and on-chain balances on the homepage

### ISSUE THREAD

**Issue by shesek** [shesek/spark-wallet#67]
Maybe something like this, below the main pay/receive buttons:

```
       off-chain                     on-chain

      5,500 bits                     800 bits
     in 5 channels                 in 2 outputs
```

The number of channels/outputs could perhaps be displayed in "expert mode" only.

**Comment by yoss1x** [comment]
How about having them on top, instead of the total-balance?
Maybe something like this: https://codepen.io/anon/pen/oVWXje

![screenshot from 2019-03-08 01-43-56](https://user-images.githubusercontent.com/42577881/53998774-96353c00-4149-11e9-841b-dd6a66f167b8.png)

"⚡ off-chain" links to Channels page.
Content might be too wide with some themes, maybe hide the "Sparks" banner on small screens.

**Comment by pavlenex** [comment]
This would be really nice to have.

**Comment by shesek** [comment]
I tried fitting this in the navbar, but there's not enough space to display both, especially on mobile. Note that the "Spark" link on the navbar is also used for navigating back to the homepage, so we can't remove it. I ended up adding the channel/onchain balance as a new component in the homepage (ed9566e910a410b9be8b927beac6cdbf2a66fe99), which looks like this:

![image](https://user-images.githubusercontent.com/877904/59070061-f743eb80-88c1-11e9-8d80-fc7d4136923e.png)
